import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

export const Container = styled.div`
  display: flex;
  min-height: 100vh;
`;

export const Main = styled.div`
  align-items: center;
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
  padding: 4rem 0;
`;

export const Title = styled.div`
  line-height: 1.15;
  font-size: 4rem;
  margin: 0;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>Front Template</Title>
      </Main>
    </Container>
  );
};

export default Home;
